### ISSUE TITLE
Ignores data-gif attribute

### ISSUE THREAD

**Issue by ArtS** [darthrubens/gifplayer#3]
URL in `data-gif` attribute seems to be ignored and the plugin simply attempts to load a file with .gif extension, replacing the .png extension in `src` attribute.

Looks like getGifSrc function is to blame.

**Comment by FlipZoomMedia** [comment]
I can only confirm. The data attribute has no function.

**Comment by darthrubens** [comment]
Hi , I just updated the plugin to fix this and other bugs, also include support for videos.
Please update. And thanks for your feedback.
