### ISSUE TITLE
Call function from AJAX loaded content

### ISSUE THREAD

**Issue by Unapzeus** [darthrubens/gifplayer#5]
Hello... Are you still develop this great plugin?
I Have a problem when using this plugin to load gifs in content loaded by AJAX. Using "$('body').gifplayer();" in js files inside document ready. Nothing error, but it will not works. Adding this function into success event when AJAX loaded, but it look duplicated. 

Can you give us any additional option such selector name just like bootstrap? There is bootstrap function to execute in AJAX:

$('body').tooltip({selector:'[data-toggle="tooltip"]'});

I wish gifplayer plugin have an option:
$('body').gifplayer({selector:'[gif-class="gifs"]'}); instead $('.gifs').gifplayer();

So we can bind function into AJAX without duplicate. Hope you can update this plugin.

Thank you!

**Comment by darthrubens** [comment]
Hi.
I can think of a couple solutions that don't imply changing the plugin.

1. You can add a class to the gif images you have already loaded. For example let's say the class name is 'ready'. Every time you load new elements you apply the plugin to those elements that don't have the 'ready' class yet, and then add the 'ready' class.
Something like this:
success: function(){
    $('.gif:not(.ready)').gifplayer();
    $('.gif:not(.ready)').addClass('ready');
}

2. Use a more specific selector. You might notice the gifplayer adds a wrapper div around the preview element. Use a selector that mentions the imediate parent of the preview element (without the wrapper)

$('.inmeadiate-parent > .gif').gifplayer();
